### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Cat121**
Added basic steps to create a portal.

### CODE REVIEW

**Comment by trentech** [comment]
You know the wiki section is public..seems like a more appropriate location for this, but for the sake of getting out there I'll merge this

**Comment by Cat121** [comment]
My bad... I will publish on the wiki for the next pulls !

**Comment by trentech** [comment]
I welcome the contribution. It's no secret I'm a slacker when it comes to documentation

**Comment by Cat121** [comment]
I am more a documentation guy, we might give pjp the glory it deserves 😄

**Pull request merged**
